### ISSUE TITLE
Request had insufficient authentication scopes

### ISSUE THREAD

**Issue by githerbert** [St3ph-fr/my-apps-script-utils#10]
Hello, I followed the instructions and every other function except the **setSecurityGroups** runs properly, when running this I get the following:

{"error":{"code":403,"message":"Request had insufficient authentication scopes.","status":"PERMISSION_DENIED"}}

I have ensured that the Cloud Identity API and Admin SDK are on.  Do you know what this might be?

**Comment by St3ph-fr** [comment]
Hi

Thank you for your feedback I forgot to change the scope you must update your appsscript.json file and change the scope https://www.googleapis.com/auth/cloud-identity.groups.readonly to the scope https://www.googleapis.com/auth/cloud-identity.groups

Stéphane
